export const ALL_CUSTOMERS_REQUEST = "ALL_CUSTOMERS_REQUEST";
export const ALL_CUSTOMERS_SUCCESS = "ALL_CUSTOMERS_SUCCESS";
export const ALL_CUSTOMERS_FAILURE = "ALL_CUSTOMERS_FAILURE";

export const CREATE_CUSTOMERS_REQUEST = "CREATE_CUSTOMERS_REQUEST";
export const CREATE_CUSTOMERS_SUCCESS = "CREATE_CUSTOMERS_SUCCESS";
export const CREATE_CUSTOMERS_FAILURE = "CREATE_CUSTOMERS_FAILURE";

export const UPDATE_CUSTOMERS_REQUEST = "UPDATE_CUSTOMERS_REQUEST";
export const UPDATE_CUSTOMERS_SUCCESS = "UPDATE_CUSTOMERS_SUCCESS";
export const UPDATE_CUSTOMERS_FAILURE = "UPDATE_CUSTOMERS_FAILURE";

export const DELETE_CUSTOMERS_REQUEST = "DELETE_CUSTOMERS_REQUEST";
export const DELETE_CUSTOMERS_SUCCESS = "DELETE_CUSTOMERS_SUCCESS";
export const DELETE_CUSTOMERS_FAILURE = "DELETE_CUSTOMERS_FAILURE";

export const CUSTOMER_DETAILS_REQUEST = "CUSTOMER_DETAILS_REQUEST";
export const CUSTOMER_DETAILS_SUCCESS = "CUSTOMER_DETAILS_SUCCESS";
export const CUSTOMER_DETAILS_FAILURE = "CUSTOMER_DETAILS_FAILURE";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
